language: node_js
node_js:
    - 12
cache: yarn
install:
    - yarn
script:
    - yarn build
after_success:
    - cd docs/.vuepress/dist
    - git init
    - git config --global user.name "${GIT_NAME}"
    - git config --global user.email "${GIT_EMAIL}"
    - git add -A
    - git commit -m 'deploy'
    - git push --quiet --force "https://${GH_TOKEN}@${GH_REPO}" master:${GIT_BRANCH}
branches:
  only:
    - docs
